### ISSUE TITLE
Not compatible with RN 0.63.4+

### ISSUE THREAD

**Issue by PaulIvanov** [tessus/react-native-version-info#10]
I tried following the steps to link the library into my app and ran into an issue with my IOS build:
```
../../react-native/React/Base/RCTBridgeModule.h:10:9: fatal error: 'React/RCTDefines.h' file not found
#import <React/RCTDefines.h>
        ^~~~~~~~~~~~~~~~~~~~
1 error generated.
```

Based on my investigation, it looks like the React Native project was deprecated in 0.61, but i very likely could be doing something wrong.

**Comment by tessus** [comment]
I can't reproduce this. We are using the module in Joplin with react-native 0.64.2

**Comment by EricTorresAndrade** [comment]
same issue

**Comment by daniel-keen** [comment]
Having the same problem. "react-native": "0.71.8",
Following the installation step by step has led me to this issue:
**React/RCTDefines.h' file not found**

**Comment by tessus** [comment]
I still can't reproduce this. This is also used in the [Joplin](https://github.com/laurent22/joplin) project (see [mobile version](https://github.com/laurent22/joplin/blob/dfbe62894472eb0a4771cabc490a00b98965ae1d/packages/app-mobile/package.json#L69)).

I suspect that there is something weird going on with the OP's and your environments, otherwise I would get the same error, wouldn't I?

I really would love to help, but I just don't know how, if I don't encounter this issue.
