### ISSUE TITLE
iOS : returns 'undefined' - automatic linking

### ISSUE THREAD

**Issue by gauthampait** [tessus/react-native-version-info#6]
Tried the latest but returns undefined on iOS with react-native version 59. Works fine on Android. Seems like react-native link for iOS isn't working I believe though it does add the node_module link in the pod file . Did not the manual linking method.

**Comment by tessus** [comment]
Did you read https://github.com/tessus/react-native-version-info/issues/3#issuecomment-438883751 ? This might very well be an upstream issue. Linking with iOS seems to be a problem with a bunch of modules.

I know for a fact that the manual method works, since we use it in the project Joplin.

Of course I have to make sure that the automatic method also works.

Can you please check if using the automatic method did everything that would have been done in the manual steps?

**Comment by tessus** [comment]
Still waiting for feedback. If I don't receive any input in the next 48h, I will close this issue.

**Comment by gauthampait** [comment]
Sorry for the late reply. I was out of town. I am gonna test it today.

**Comment by tessus** [comment]
This is a known react-native issue. There's nothing I can do about it.

I have seen the `pod update` solution in several stackoverflow topics. But maybe I could add that info to the README. I'm not sure, if I should put it in the FAQ or the automatic linking section. What do you think?

Should I add something like:

If you are using pods, don't forget to run `pod update`.

**Comment by tessus** [comment]
Added info to README.md - see 5082288f7b5f98e86229f63519cd17c27c29d91c

**Comment by gauthampait** [comment]
I think we just add reference to this issue in a Troubleshooting section and call it a day. Works ?

**Comment by tessus** [comment]
I had already added it to the README...
